### ISSUE TITLE
[SplashScreen] No imaging component suitable to complete this operation was found

### ISSUE THREAD

**Issue by darklinkpower** [darklinkpower/PlayniteExtensionsCollection#240]
### Extension name

SplashScreen

### Bug Description

Crash: No imaging component suitable to complete this operation was found

Happens in https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/f83bf487885032651d5f5f9a68f09de6be785fc6/source/Generic/SplashScreen/Views/SplashScreenImage.xaml.cs#L30

### To Reproduce

No idea. No one has reported it.

### Extensions log

```
19-02 11:33:10.161|ERROR|PlayniteApplication:Unhandled exception occured.
System.NotSupportedException: No imaging component suitable to complete this operation was found. ---> System.Runtime.InteropServices.COMException: The component initialization has failed. (Exception from HRESULT: 0x88982F8B)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at SplashScreen.Views.SplashScreenImage..ctor(SplashScreenSettings settings, String splashImagePath, String logoPath) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\Views\SplashScreenImage.xaml.cs:line 30
   at SplashScreen.SplashScreen.<>c__DisplayClass19_0.<CreateSplashImageWindow>b__0() in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\SplashScreen.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
```

**Comment by darklinkpower** [comment]
Fixed
