### ISSUE TITLE
[JAST USA] Exception parsing API results

### ISSUE THREAD

**Issue by chirin1234** [darklinkpower/PlayniteExtensionsCollection#430]
### Extension name

JAST USA

### Bug Description
```
Failed to import games from plugin: JAST USA
Newtonsoft.Json.JsonSerializationException: Error converting value "/api/v2/contexts/Result" to type 'JastUsaLibrary.Models.Context'. Path '@context', line 1, position 41. ---> System.ArgumentException: Could not cast or convert from System.String to JastUsaLibrary.Models.Context
```
Seems like an API change?

### To Reproduce

Attempt to update JAST library.

### Logs

API response has been edited to only show the first product result for brevity.

```31-08 17:32:32.393|DEBUG|Serialization:{ "@context": "\/api\/v2\/contexts\/Result", "@id": "\/api\/v2\/shop\/search\/products\/7", "@type": "Result", "products": [{ "@id": "\/api\/v2\/shop\/products\/srvn017", "@type": "Product", "variants": [ { "@id": "\/api\/v2\/shop\/product-variants\/srvn017", "@type": "ProductVariant", "game": { "@id": "\/api\/v2\/shop\/games\/608", "@type": "Game", "translations": { "en_US": { "@id": "\/api\/v2\/shop\/account\/game-translations\/698", "@type": "GameLinkTranslation", "id": 698, "locale": "en_US" } } }, "inStock": true, "price": 0, "originalPrice": 0, "productName": "Megasuki: Love Through Lenses with Ayumu Sakura", "productVariantName": null, "productImage": "3d\/9a\/b47a84a9d145466c44291a0de9a3.png", "productImageBackground": null, "platforms": [ { "en_US": "Windows" } ], "productCode": "srvn017", "gameId": 608, "userGameTags": [], "hasPatches_en_US": false, "hasPatches_zh_Hans": false, "hasPatches_zh_Hant": false } ], "variant": { "@id": "\/api\/v2\/shop\/product-variants\/srvn017", "@type": "ProductVariant", "game": { "@id": "\/api\/v2\/shop\/games\/608", "@type": "Game", "translations": { "en_US": { "@id": "\/api\/v2\/shop\/account\/game-translations\/698", "@type": "GameLinkTranslation", "id": 698, "locale": "en_US" } } }, "inStock": true, "price": 0, "originalPrice": 0, "productName": "Megasuki: Love Through Lenses with Ayumu Sakura", "productVariantName": null, "productImage": "3d\/9a\/b47a84a9d145466c44291a0de9a3.png", "productImageBackground": null, "platforms": [ { "en_US": "Windows" } ], "productCode": "srvn017", "gameId": 608, "userGameTags": [], "hasPatches_en_US": false, "hasPatches_zh_Hans": false, "hasPatches_zh_Hant": false } }], "attributes": [ [ { "@type": "Attribute", "name": "Genre", "values": [], "code": "17", "position": 10 } ], [ { "@type": "Attribute", "name": "Tags", "values": [ { "@type": "AttributeValue", "label": "adventure", "code": "14_12bbb94c-309f-11ec-9126-5a000385a85f", "counter": 14 }, { "@type": "AttributeValue", "label": "comedy", "code": "14_35a39414-591e-11ec-b732-5a000385a85f", "counter": 38 }, { "@type": "AttributeValue", "label": "drama", "code": "14_35a3a012-591e-11ec-83b3-5a000385a85f", "counter": 34 }, { "@type": "AttributeValue", "label": "fantasy", "code": "14_35a3a6de-591e-11ec-bfa0-5a000385a85f", "counter": 30 }, { "@type": "AttributeValue", "label": "horror", "code": "14_35a3addc-591e-11ec-b218-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "mystery", "code": "14_35a3b43a-591e-11ec-999d-5a000385a85f", "counter": 11 }, { "@type": "AttributeValue", "label": "nakige", "code": "14_35a3ba84-591e-11ec-8938-5a000385a85f", "counter": 6 }, { "@type": "AttributeValue", "label": "nukige", "code": "14_35a3c196-591e-11ec-afce-5a000385a85f", "counter": 59 }, { "@type": "AttributeValue", "label": "romance", "code": "14_35a3c7e0-591e-11ec-9a41-5a000385a85f", "counter": 53 }, { "@type": "AttributeValue", "label": "sci-fi", "code": "14_35a3ce16-591e-11ec-8e72-5a000385a85f", "counter": 8 }, { "@type": "AttributeValue", "label": "slice of life", "code": "14_35a3d546-591e-11ec-927b-5a000385a85f", "counter": 20 }, { "@type": "AttributeValue", "label": "visual novel", "code": "14_35a3dba4-591e-11ec-a93d-5a000385a85f", "counter": 117 }, { "@type": "AttributeValue", "label": "rpg", "code": "14_35a3e1e4-591e-11ec-beed-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "strategy", "code": "14_35a3ee32-591e-11ec-9c9b-5a000385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "yuri", "code": "14_35a3fbd4-591e-11ec-94da-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "BL", "code": "14_35a4020a-591e-11ec-91b0-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "kinetic", "code": "14_35a4082c-591e-11ec-9950-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "few choices", "code": "14_35a40e62-591e-11ec-9373-5a000385a85f", "counter": 11 }, { "@type": "AttributeValue", "label": "many endings", "code": "14_35a41524-591e-11ec-a658-5a000385a85f", "counter": 29 }, { "@type": "AttributeValue", "label": "animation", "code": "14_35a41ba0-591e-11ec-a3bc-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "animal ears", "code": "14_35a422c6-591e-11ec-97ac-5a000385a85f", "counter": 4 }, { "@type": "AttributeValue", "label": "monsters", "code": "14_35a42b40-591e-11ec-9b2e-5a000385a85f", "counter": 10 }, { "@type": "AttributeValue", "label": "vampires", "code": "14_35a4319e-591e-11ec-90b9-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "sfw", "code": "14_35a4381a-591e-11ec-b14c-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "nsfw", "code": "14_35a43e50-591e-11ec-863d-5a000385a85f", "counter": 122 }, { "@type": "AttributeValue", "label": "mosaics", "code": "14_35a4447c-591e-11ec-b0b6-5a000385a85f", "counter": 14 }, { "@type": "AttributeValue", "label": "no mosaics", "code": "14_35a44af8-591e-11ec-9c0e-5a000385a85f", "counter": 107 }, { "@type": "AttributeValue", "label": "gore", "code": "14_35a45192-591e-11ec-8133-5a000385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "corruption", "code": "14_031fbc20-5bc1-11ec-99a5-5a000385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "genderbending", "code": "14_031fc31e-5bc1-11ec-93c8-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "female protagonist", "code": "14_c645d2a2-5ef5-11ec-9e2e-5a000385a85f", "counter": 5 } ], "code": "14", "position": 20 } ], [ { "@type": "Attribute", "name": "Studio", "values": [ { "@type": "AttributeValue", "label": "Nitro+chiral", "code": "3_4ee590be-03f4-11ec-83e4-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Lyricbox", "code": "3_967bd4a6-03f4-11ec-a9bc-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Frontwing", "code": "3_a987336a-03f4-11ec-b760-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "D.O.", "code": "3_b8b1bca2-03f4-11ec-abed-5a010385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "ZyX", "code": "3_b9c05d1a-03f4-11ec-af56-5a010385a85f", "counter": 8 }, { "@type": "AttributeValue", "label": "Angel Smile", "code": "3_bac84ee8-03f4-11ec-8b1c-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Trabulance", "code": "3_bc31ad2e-03f4-11ec-9268-5a010385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "Sekilala", "code": "3_bf08a9a8-03f4-11ec-855d-5a010385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "Ignition", "code": "3_c6677fe4-03f4-11ec-8b6f-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Yamikumo-Communications", "code": "3_c993ecac-03f4-11ec-957e-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Mercure", "code": "3_ca057688-03f4-11ec-8d60-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Alcot", "code": "3_e9f66b96-03f4-11ec-b6d5-5a010385a85f", "counter": 4 }, { "@type": "AttributeValue", "label": "Xuse", "code": "3_eca98986-03f4-11ec-bf57-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "0verflow", "code": "3_ef1334b0-03f4-11ec-b0c8-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Empress", "code": "3_f62ec566-03f4-11ec-a9ed-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Code Pink", "code": "3_fb1fbcce-03f4-11ec-a5ad-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Nitro Origin", "code": "3_feb274c6-03f4-11ec-a845-5a010385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "Tenco", "code": "3_0170b24a-03f5-11ec-93ec-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Poison@Berry", "code": "3_058b51e6-03f5-11ec-8260-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Petit Pajamas", "code": "3_0a28751c-03f5-11ec-9e7b-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Vanadis", "code": "3_11122d32-03f5-11ec-86e2-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Minato Soft", "code": "3_1a6bc140-03f5-11ec-9b9f-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "monoceros+", "code": "3_2352c68c-03f5-11ec-9ed6-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Black Cyc", "code": "3_2e7a8fc2-03f5-11ec-b517-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Laplacian", "code": "3_39ca03ee-03f5-11ec-86d7-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "CHAOS-L", "code": "3_42a05cac-03f5-11ec-9b37-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Ninetail", "code": "3_fbdb06f2-03f7-11ec-8ed3-5a010385a85f", "counter": 7 }, { "@type": "AttributeValue", "label": "Crowd", "code": "3_419bac78-03f8-11ec-99e8-5a010385a85f", "counter": 6 }, { "@type": "AttributeValue", "label": "Sweet Basil", "code": "3_43b06ba2-03f8-11ec-b766-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Guilty", "code": "3_47a1afe6-03f8-11ec-bfbc-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "rúf", "code": "3_548a6e14-03f8-11ec-900a-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "TOP", "code": "3_5a44464a-03f8-11ec-956b-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "t japan", "code": "3_960bc414-03f8-11ec-b1d9-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Toffer Team", "code": "3_c566dec4-03f8-11ec-bea3-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Epic Works", "code": "3_d31c1fb6-03f8-11ec-9ef3-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Yume Creations", "code": "3_f92b2b5c-03f8-11ec-ab92-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "CHAOS-R", "code": "3_86a23b12-3066-11ec-bfdb-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Escu:de", "code": "3_69b2d1ae-3e00-11ec-baaa-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "metalogiq", "code": "3_696deb1c-5e25-11ec-927d-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Minato Carnival World", "code": "3_101f7d70-69ef-11ec-90fe-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Four Leaf Studios", "code": "3_14f810a2-6db7-11ec-88ac-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Alice Soft", "code": "3_efbc0f92-78aa-11ec-ae6a-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "Pajama EX", "code": "3_a13cb374-84af-11ec-871f-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Tinkerbell", "code": "3_51d31ff4-1e6e-11ed-9ac2-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Marmalade", "code": "3_3da7d470-3a38-11ee-a54e-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "GLASSES", "code": "3_391e1bc8-42a6-11ee-97b8-5a000385a85f", "counter": 3 } ], "code": "3", "position": 30 } ], [ { "@type": "Attribute", "name": "Publisher", "values": [ { "@type": "AttributeValue", "label": "JAST BLUE", "code": "2_4ee585d8-03f4-11ec-88a4-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "FAKKU", "code": "2_96165fe0-03f4-11ec-a229-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Frontwing", "code": "2_a9872604-03f4-11ec-8196-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "JAST USA", "code": "2_b8b1b270-03f4-11ec-942d-5a010385a85f", "counter": 98 }, { "@type": "AttributeValue", "label": "Love Lab", "code": "2_eea45314-03f5-11ec-a862-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "MediBang", "code": "2_f14ca382-03f5-11ec-9b28-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "NekoNyan", "code": "2_ff1a32ca-03f7-11ec-a166-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Denpasoft", "code": "2_7db9a8e0-03f8-11ec-8a01-5a010385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Sol Press", "code": "2_af22bb42-03f8-11ec-804d-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Toffer Team", "code": "2_c566b2be-03f8-11ec-bef7-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Top Hat Curios", "code": "2_d31bf7ac-03f8-11ec-b13f-5a010385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Yume Creations", "code": "2_f92b0348-03f8-11ec-bfbb-5a010385a85f", "counter": 3 }, { "@type": "AttributeValue", "label": "Alice Soft", "code": "2_c20d344a-78aa-11ec-8a3d-5a000385a85f", "counter": 4 }, { "@type": "AttributeValue", "label": "Shiravune", "code": "2_fff8a764-2cde-11ee-aa97-5a000385a85f", "counter": 9 } ], "code": "2", "position": 40 } ], [ { "@type": "Attribute", "name": "Platform", "values": [ { "@type": "AttributeValue", "label": "Windows", "code": "4_3e046090-03f4-11ec-b2a5-5a010385a85f", "counter": 127 }, { "@type": "AttributeValue", "label": "Mac", "code": "4_d2507354-049b-11ec-9e35-5a000385a85f", "counter": 5 }, { "@type": "AttributeValue", "label": "Linux", "code": "4_d2508b50-049b-11ec-875c-5a000385a85f", "counter": 5 } ], "code": "4", "position": 50 } ], [ { "@type": "Attribute", "name": "Supported Languages", "values": [ { "@type": "AttributeValue", "label": "English", "code": "15_60f26da0-42af-11ec-961e-5a000385a85f", "counter": 126 }, { "@type": "AttributeValue", "label": "Japanese", "code": "15_60f27480-42af-11ec-a166-5a000385a85f", "counter": 2 }, { "@type": "AttributeValue", "label": "Simplified Chinese", "code": "15_60f278fe-42af-11ec-bfe8-5a000385a85f", "counter": 13 }, { "@type": "AttributeValue", "label": "Traditional Chinese", "code": "15_60f27d7c-42af-11ec-840a-5a000385a85f", "counter": 12 }, { "@type": "AttributeValue", "label": "French", "code": "15_9294556c-6dc0-11ec-a257-5a000385a85f", "counter": 1 }, { "@type": "AttributeValue", "label": "Spanish", "code": "15_92946494-6dc0-11ec-86d0-5a000385a85f", "counter": 1 } ], "code": "15", "position": 60 } ] ], "total": 129, "pages": 7 }
31-08 17:32:32.393|ERROR|MainViewModelBase:Failed to import games from plugin: JAST USA
Newtonsoft.Json.JsonSerializationException: Error converting value "/api/v2/contexts/Result" to type 'JastUsaLibrary.Models.Context'. Path '@context', line 1, position 41. ---> System.ArgumentException: Could not cast or convert from System.String to JastUsaLibrary.Models.Context.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at JastUsaLibrary.Services.JastUsaAccountClient.GetGames(AuthenticationToken authenticationToken) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Library\JastUsaLibrary\Services\JastUsaAccountClient.cs:line 232
   at JastUsaLibrary.JastUsaLibrary.GetGames(LibraryGetGamesArgs args) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Library\JastUsaLibrary\JastUsaLibrary.cs:line 84
   at Playnite.Database.GameDatabase.ImportGames(LibraryPlugin library, CancellationToken cancelToken, PlaytimeImportMode playtimeImportMode) in C:\projects\playnite\source\Playnite\Database\GameDatabase.cs:line 1223
   at Playnite.ViewModels.MainViewModelBase.ImportLibraryGames(LibraryPlugin plugin, CancellationToken token) in C:\projects\playnite\source\Playnite\ViewModels\MainViewModelBase.cs:line 506```

### Screenshots

_No response_

**Comment by darklinkpower** [comment]
Fixed in v1.11. There were many changes that needed to be made but unfortunately I don't have games on JAST USA, I only used the free items available on the store like demos and patches to develop and test and while I made sure everything worked correctly there's the chance that there could be an issue with people with larger libraries. Please update and test if it's working correctly, it it works fine let me know to close the issue.

Tagging @Seany1990 as well.

**Comment by Seany1990** [comment]
It is working for me. Thank you for fixing the bug

**Comment by chirin1234** [comment]
Looks good to me. thank you. You can  go ahead and close the issue.

**Comment by darklinkpower** [comment]
Thanks for checking.
