### ISSUE TITLE
[Playstate] Crashes Playnite on Windows 11

### ISSUE THREAD

**Issue by JustThat70** [darklinkpower/PlayniteExtensionsCollection#483]
### Extension name

Playstate

### Bug Description

When I install Playstate into Playnite on Windows 11 and restart, Playnite goes into a crash loop.

I know this extension works on Windows 11 as I have it on another system

### To Reproduce

1. Install playnite
2. Launch playnite
3. Add playstate extension
4. Relaunch playnite

### Logs

28-12 23:26:33.195|ERROR|PlayniteApplication:Unhandled exception occured.
System.DllNotFoundException: Unable to load DLL 'XInputInterface': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at PlayState.XInputDotNetPure.Imports.XInputGamePadGetState(UInt32 playerIndex, RawState& state)
   at PlayState.GamePadHandler.<CheckControllersAsync>d__9.MoveNext() in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\PlayState\GamePadHandler.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PlayState.GamePadHandler.<OnControllerTimerElapsed>d__8.MoveNext() in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\PlayState\GamePadHandler.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13791239/playnite.log)

**Comment by JustThat70** [comment]
Update: I've fixed this by moving the XinputInterface.dll from an old installation of Playnite into the new installation's app folder.

Not sure, but Playnite may no longer include this .dll
