### ISSUE TITLE
[Steam Search] Extension "Steam Search" failed to load properly

### ISSUE THREAD

**Issue by EvilNick2** [darklinkpower/PlayniteExtensionsCollection#514]
### Extension name

Steam Search

### Bug Description

When installing the Steam Search extension it completely fails to load without any chance for the extension to initialise.

### Logs

```log
20-03 09:04:21.601|ERROR|ExtensionFactory:Failed to load plugin: Steam Search
System.ArgumentException: Customized cultures cannot be passed by LCID, only by name.
Parameter name: culture
   at System.Globalization.RegionInfo..ctor(Int32 culture)
   at SteamSearch.SteamSearchSettingsViewModel.<>c.<.ctor>b__13_0(CultureInfo x) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SteamSearch\SteamSearchSettings.cs:line 61
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at SteamSearch.SteamSearchSettingsViewModel..ctor(SteamSearch plugin) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SteamSearch\SteamSearchSettings.cs:line 62
   at SteamSearch.SteamSearch..ctor(IPlayniteAPI api) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SteamSearch\SteamSearch.cs:line 25
```

**Comment by darklinkpower** [comment]
I can't reproduce it and I have no idea why no one else has had this issue before but I made some changes to hopefully fix the issue and released an update. Please let me know if it's fixed for you to close the issue.

**Comment by EvilNick2** [comment]
The update fixed the issue of the add-on not loading! Many thanks
