### ISSUE TITLE
[Splash Screen] Error during sorting when opening Video manager

### ISSUE THREAD

**Issue by SuperJayRay** [darklinkpower/PlayniteExtensionsCollection#92]
**Extension**
Splash Screen

**Describe the bug**
When I open video manager, it gives me "Failed to Execute Menu Action.  Failed to Compare two elements in array."

**To Reproduce**
Open video manager after adding several videos through manager or file explorer.

**Expected behavior**
See  video manager and manager videos.

**Extensions log**
```
01-11 11:55:57.642|ERROR|MainMenu:Main menu extension action failed.
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SplashScreen.ViewModels.VideoManagerViewModel.<>c.<.ctor>b__38_0(VideoManagerItem x, VideoManagerItem y) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\ViewModels\VideoManagerViewModel.cs:line 229
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at SplashScreen.ViewModels.VideoManagerViewModel..ctor(IPlayniteAPI api) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\ViewModels\VideoManagerViewModel.cs:line 229
   at SplashScreen.SplashScreen.OpenVideoManager() in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\SplashScreen.cs:line 456
   at SplashScreen.SplashScreen.<GetMainMenuItems>b__23_0(MainMenuItemActionArgs a) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\SplashScreen\SplashScreen.cs:line 423
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass18_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:line 387
```

**Comment by darklinkpower** [comment]
Can you send me your Playnite library directory without the files directory in it to try to solve the issue? You can send it here or over the Playnite discord.

**Comment by darklinkpower** [comment]
Closing as there was no reply.
